name = "a0b_armv7m"
description = "A0B: ARMv7-M support (Cortex-M3, Cortex-M4, Cortex-M7)"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files=["gnat/a0b_armv7m.gpr"]

tags = ["embedded"]

[configuration]
generate_ada = false
generate_gpr = true
generate_c = false

[configuration.variables]
FPU_Extension = {type = "Enum", values = ["none", "VFPv4", "VFPv5"]}

[[depends-on]]
gnat_arm_elf = "*"
a0b_base = "*"

[[actions]]
type = "test"
directory = "selftest"
command = ["alr", "build"]
